default: &default
  adapter: postgresql
  encoding: unicode
  user: sammara
  password: 040622
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: library_development
